# -*- coding: utf-8 -*-
"""loadDataFromDrive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AofPGf0l9dPOSHMLeWG8cSOT7FSBBmMu
"""

!pip install -U -q PyDrive ## you will have install for every colab session

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

import cv2

#1aJcfwNpf26ewVksuN2yQofg3Pgww8iB5

import_image = drive.CreateFile({'id':'1aJcfwNpf26ewVksuN2yQofg3Pgww8iB5'})

import_image.GetContentFile('pic.jpg')

#sample_uploaded_data = json.load(open('sample.json'))
sample_data = cv2.imread('pic.jpg')

print(sample_data)

