# -*- coding: utf-8 -*-
"""Model summary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N6FJ-4HL8mEyXlSBr6PZO-CIIlK01I-k
"""

# import modules
from keras.models import Sequential, load_model
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.layers.normalization import BatchNormalization
from keras import optimizers
import keras

from keras.applications.vgg16 import VGG16

model = VGG16(weights='imagenet', include_top=False)

import pydot
import graphviz
from keras.utils import plot_model
plot_model(model, show_shapes=True, show_layer_names=True, to_file='model.png')

!pip install -r requirements.txt



